#!/bin/bash

# Implement readlink which does not work on mac os https://stackoverflow.com/a/1116890
# This gives us flexibility to change the Java code and recompile a jar that we can test via `./alan`
# without blowing away our stable, globally-installed version
TARGET_FILE=$0

ORIG_DIR=`pwd -P`

cd `dirname $TARGET_FILE`
TARGET_FILE=`basename $TARGET_FILE`

# Iterate down a (possible) chain of symlinks
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=`readlink $TARGET_FILE`
    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`
done

# Compute the canonicalized name by finding the physical path
# for the directory we're in and appending the target file.
PHYS_DIR=`pwd -P`

# Restore the original directory so the script referenced can be found
cd $ORIG_DIR

allargs=$@
del=$1
args=( "${allargs[@]/$del}" )

case $1 in
  compile)
    alan-compile $args out.agc # TODO: allow output file to be specified
    ;;

  transpile-amm)
    alan-compile $args out.amm # TODO: allow output file to be specified
    ;;

  transpile-js)
    alan-compile $args out.js # TODO: allow output file to be specified
    ;;

  install)
    DEP_FILE=./.dependencies.ln
    if [ -f "$DEP_FILE" ]; then
        alan-compile $DEP_FILE out.agc
        alan-runtime run out.agc
        rm out.agc
        exit 0
    else
        echo "$DEP_FILE does not exist. Dependencies can only be installed for .dependencies.ln"
        exit 1
    fi
    ;;

  run)
    alan-runtime run $args
    ;;

  help)
    echo "alan Usage:"
    echo "alan compile path/to/sourcefile.ln        - Loads the specified source file and builds an output alan graphcode file"
    echo "alan transpile-amm path/to/sourcefile.ln  - Loads the specified source file and builds an output alan intermediate representation file"
    echo "alan transpile-js path/to/sourcefile.ln   - Loads the specified source file and builds an output javascript file"
    echo "alan install                              - Install '/dependencies' from '.dependencies.ln'"
    echo "alan run path/to/compiled.agc             - Loads and runs the specified build file"
    echo "alan help                                 - Prints this message"
    exit 0
    ;;

  *)
    echo "Unknown command. Run 'alan help' to get a list of commands"
    exit 1
    ;;
esac
