[package]
name = "alan"
description = "The Alan Compiler"
license = "MIT"
homepage = "https://alan-lang.org"
documentation = "https://docs.alan-lang.org"
repository = "https://github.com/alantech/alan"
version = "0.2.0"
authors = ["David Ellis <isv.damocles@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dirs = "5.0.1"
nom = "7.1.3"
ordered_hash_map = "0.4.0"
rand = "0.8.5"
sysinfo = "0.30.7"

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "map"
harness = false
