name: Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v4
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench
    - name: Build Alan-managed Benchmarks
      run: cargo run -- compile benches/bench.ln
    - name: Alan-managed Benchmarks
      run: ./bench

  bench-windows:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v4
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench

  bench-macos:
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v4
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench
