name: Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: ${{ github.workspace }}/.cargo

jobs:
  bench:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update branch URLs for testing
      run: ./scripts/update_branch_urls.sh
    - name: Check and set Rust version
      run: ./scripts/check_rust_version.sh
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench
    - name: Build Alan-managed Benchmarks
      run: cargo run -- compile alan/benches/bench.ln && cargo run -- compile alan/benches/buffer_shader_timings.ln
    - name: Alan-managed Benchmarks
      run: ./bench && ./buffer_shader_timings

  bench-windows:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update branch URLs for testing
      run: ./scripts/update_branch_urls.sh
    - name: Check and set Rust version
      run: ./scripts/check_rust_version.ps1
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench

  bench-macos:
    runs-on: [self-hosted, macOS, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update branch URLs for testing
      run: ./scripts/update_branch_urls.sh
    - name: Check and set Rust version
      run: ./scripts/check_rust_version.sh
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench

  bench-arm-linux:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update branch URLs for testing
      run: ./scripts/update_branch_urls.sh
    - name: Check and set Rust version
      run: ./scripts/check_rust_version.sh
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench

  bench-arm-macos:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Update branch URLs for testing
      run: ./scripts/update_branch_urls.sh
    - name: Check and set Rust version
      run: ./scripts/check_rust_version.sh
    - name: Build Alan
      run: cargo build --verbose
    - name: Rust-managed Benchmarks
      run: cargo bench
    - name: Build Alan-managed Benchmarks
      run: cargo run -- compile alan/benches/bench.ln && cargo run -- compile alan/benches/buffer_shader_timings.ln
    - name: Alan-managed Benchmarks
      run: ./bench && ./buffer_shader_timings
