name: JS STDLIB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-js-stdlib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install deps
      run: pnpm install --frozen-lockfile
    - name: Run tests
      run: pnpm test
  test-js-gpgpu:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install deps
      run: pnpm install --frozen-lockfile
    - name: Bundle stdlib
      run: pnpm bundle
    - name: Set up Playwright
      run: pnpm exec playwright install
    - name: Start webserver
      run: pnpm start-server
    - name: Test GPGPU
      run: pnpm test-gpgpu
    - name: Stop webserver
      if: always()
      run: pnpm stop-server
