name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - if: {{ github.ref == 'ref/head/main' }}
      name: Run tests
      run: cargo test --verbose -- --ignored
    - if: {{ github.ref != 'ref/head/main' }}
      name: Run tests
      run: cargo test --verbose
