name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - if: ${{ github.ref_name == 'main' }}
      name: Run tests
      run: cargo test --verbose -- --include-ignored
    - if: ${{ github.ref_name != 'main' }}
      name: Run tests
      run: cargo test --verbose

  test-windows:
    runs-on: [self-hosted, windows]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - if: ${{ github.ref_name == 'main' }}
      name: Run tests
      run: cargo test --verbose -- --include-ignored
    - if: ${{ github.ref_name != 'main' }}
      name: Run tests
      run: cargo test --verbose

  test-macos:
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@v4
    - name: Node deps
      run: yarn
    - name: Build
      run: cargo build --verbose
    - if: ${{ github.ref_name == 'main' }}
      name: Run tests
      run: cargo test --verbose -- --include-ignored
    - if: ${{ github.ref_name != 'main' }}
      name: Run tests
      run: cargo test --verbose

  test-arm-linux:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - if: ${{ github.ref_name == 'main' }}
      name: Run tests
      run: RUST_MIN_STACK=8388608 cargo test --verbose -- --include-ignored
    - if: ${{ github.ref_name != 'main' }}
      name: Run tests
      run: RUST_MIN_STACK=8388608 cargo test --verbose
