name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  craziness:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v4
    - name: Craziness
      run: chmod 600 ~/.ssh/authorized_keys
